### ISSUE TITLE
Expiring system slowdown after adding vulcan integration

### ISSUE THREAD

**Issue by pniewiadowski** [Czapla-dev/vulcan-for-hassio#1]
Hi,

first of all thank you for this amazing integration, although I have noticed some performance problems after adding the integration to my HA instance.
The whole system slow down significantly and I can not see any impact from hardware perspective. 
The CPU/MEM/Drive seems to be on the same utilization level but the system response is worst.

I can see even poor performance on such events like motion detection or delay on light on event.

What I have noticed is that once I add the integration via "Setting -> Integration -> +" it doesn't have impact on system but the entities are not in the HA - means doesn't pull the information from vulcan. 
Then, I add the configuration (like below) in the configuration.yaml, and HA becomes to be very slow, but the entities with lesson plan are available.

```
vulcan:
  token: token
  symbol: symbol
  pin: pin
```

Please let me know if you can confirm this, or please give me some instruction as how I can try to dubug this on my end.
I am more than happy to help solve this out.

**Comment by Czapla-dev** [comment]
I know about this problem, it is related to the Vulcan API which I am using to download data. If you want help with this, you can install beta version and check if the problem has disappeared https://github.com/Czapla-dev/vulcan-for-hassio/releases/tag/v0.2.1.beta.1

**Comment by pniewiadowski** [comment]
Beta installed, but unfortunately doesn't seem to resolve the issue.

**Comment by Czapla-dev** [comment]
I will try to fix this soon

**Comment by Czapla-dev** [comment]
https://github.com/Czapla-dev/vulcan-for-hassio/releases/tag/v0.3beta

**Comment by Czapla-dev** [comment]
https://github.com/Czapla-dev/vulcan-for-hassio/releases/tag/v0.4
