### ISSUE TITLE
Lessons - wrong order

### ISSUE THREAD

**Issue by pniewiadowski** [Czapla-dev/vulcan-for-hassio#2]
Hi Czapla,

Today (Friday) I can see the lessons for today are from yesterday (Thursday) and the lessons for tomorrow are from today (Friday).
Seems the order is mismatched.
Are you able to confirm that too?

![image](https://user-images.githubusercontent.com/28837813/93564712-70b5ff00-f98a-11ea-8d49-2c15890f4175.png)

**Comment by Czapla-dev** [comment]
Try to add integration again / restart home Assistant. Everything works fine for me.

**Comment by Czapla-dev** [comment]
Install this version: https://github.com/Czapla-dev/vulcan-for-hassio/releases/tag/v0.4
