### ISSUE TITLE
[Q] Integration config UI or YAML

### ISSUE THREAD

**Issue by ciechompl** [Czapla-dev/vulcan-for-hassio#3]
should config be done via UI or YAML ? 
Description suggest that via UI but I don't see it on the list 

![image](https://user-images.githubusercontent.com/27088154/95602665-86808680-0a55-11eb-9bf7-b5189a6e356f.png)
Integration installed via HACS 

![image](https://user-images.githubusercontent.com/27088154/95602718-9b5d1a00-0a55-11eb-8e4c-37ce81fb6f70.png)

if via YAML how to (if even possible ? :) add 2 kids into the config ? or shall i connect it to my (parent) account in UONET and will see both kids' timetables ?

**Comment by Czapla-dev** [comment]
If integration is not showing in UI try restart home assistant. Actually you can only show data for one student, you can set student name via config options.

**Comment by ciechompl** [comment]
tried ... 5 times :) .. .even reinstalled component 2 times :) still no vulcan on integration page. 
but in the notification i see this: 
![image](https://user-images.githubusercontent.com/27088154/95604502-fa239300-0a57-11eb-940b-5f723f89b9a1.png)
no errors in the log

when added just "vulcan:" only to configuration.yaml i got this error in the log:
```
2020-10-09 17:45:46 ERROR (MainThread) [homeassistant.setup] Error during setup of component vulcan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/vulcan/__init__.py", line 66, in async_setup
    for student in client.get_students():
NameError: name 'client' is not defined
```
and in notification:

![image](https://user-images.githubusercontent.com/27088154/95604950-9057b900-0a58-11eb-9506-4db8a3a3d998.png)


with full config like this:
```
vulcan:
  token: token
  symbol: symbol
  pin: pin
```
situation the same = error "name 'client' is not defined" in the log

**Comment by ciechompl** [comment]
wait .. don't know what have I done but when removed (again) config from conf yaml and rebooted again, this time I see vulcan on integration page  :)

**Comment by Czapla-dev** [comment]
If vulcan is not showing on ui integrations page please don't add it via yaml. When you install the integration in hacs and restart the HA, does something appear in the logs?

**Comment by ciechompl** [comment]
it works now ... not sure what was wrong but seem definitely my HA fault not component ...  can be closed :)
